# Generated by Django 2.2.1 on 2019-05-27 21:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20190528_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashusertoken',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
